notes/urls.py
from django.urls import path
from django.conf import settings


from . import views

app_name = 'notes'

urlpatterns = [
  path('profile/notes/all/', views.get_user_notes, name='default_user_prof'),
  path('profile/notes/<tag>/', views.get_user_notes, name='user_prof'),
  path('profile/notes/<tag>/<int:pk>/', views.user_notes_with_note_detail, name='user_prof'),
  path('profile/notes/search_res', views.get_search_results, name='search_feature'),
  path('profile/notes/search_res/<search_str>/<int:pk>', views.get_search_results_with_note_detail, 
      name='search_feature_res_det'),
  path('login/', views.AdminLogin.as_view(), name='login'),
  path('', views.home, name='home'),
  path('logout/', views.AdminLogout.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
  path('signup/', views.signup, name='signup'),
  path('add-note/', views.new_note, name='note_create'),
  path('update-note/<int:pk>', views.update_note, name='note_update'),
  path('trash/<int:pk>', views.trash_note, name='trash_note'),
  path('untrash/<int:pk>', views.untrash_note, name='untrash_note'),
  path('delete/<int:pk>', views.delete_note, name='delete_note'),
]

notes_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^markdownx/', include('markdownx.urls')),
]

notes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.conf import settings

from markdownx.models import MarkdownxField
from taggit.managers import TaggableManager
# Create your models here.

class User(AbstractUser):
  pass

class Note(models.Model):
  note_title = models.CharField(max_length=200)
  note_body = MarkdownxField()
  user = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE,
  )
  trashed = models.BooleanField(default=False)
  published = models.DateField(auto_now_add=True)
  tags = TaggableManager()

  def get_absolute_url(self):
    return reverse('notes:note_detail', kwargs={'pk': self.pk})

  def __str__(self):
    return self.note_title

notes/forms.py
from django import forms
from .models import Note
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignUpForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('username', 'password1', 'password2')

    
class NoteForm(forms.ModelForm):
  class Meta:
    model = Note
    fields = (
      'note_title',
      'note_body',
      'tags',
    )
    labels = {
      'note_title': ('Title'),
      'note_body': ('Note'),
      'tags': ('Tags'),
    }
    widgets = {
      'tags': forms.TextInput(attrs={'data-role': 'tagsinput'}),
    }
    

notes/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from markdownx.utils import markdownify


from .forms import NoteForm, SignUpForm
from .utils.helpers import queryset_ext, text_splitter, tag_extractor
from .models import Note
from taggit.models import Tag
# Create your views here.


def note_and_tag_list(request, tag):
  username = request.user
  notes_list = Note.objects.filter(user__username=username)
  tags_list = []
  for note in notes_list:
    if not note.trashed:
      note_tags = list(note.tags.all())
      note.note_tags = note.tags.all()
      for tg in note_tags:
        if tg not in tags_list:
          tags_list.append(tg)
  if tag == 'all' or tag == 'search_res':
    notes_list = notes_list.filter(trashed=False)
  elif tag == 'trash':
    notes_list = notes_list.filter(trashed=True)
  else:
    notes_list = notes_list.filter(trashed=False).filter(tags__name=tag)
  return (notes_list, tags_list)

@login_required
def get_user_notes(request, tag='all'):
  notes_list = []
  tags_list = []
  notes_list, tags_list = note_and_tag_list(request, tag)
  #print('note tags are: ', notes_list)

  for note in notes_list:
    note.nt_tags = note.tags.all()
    note.summary = text_splitter(note.note_body, 15)

  template = loader.get_template('notes/user_notes.html')
  context = {
    'notes_list': notes_list,
    'tags_list': tags_list,
    'tag_name': tag,
  }
  return HttpResponse(template.render(context, request))

@login_required
def user_notes_with_note_detail(request, tag, pk):
  notes_list = []
  tags_list = []
  notes_list, tags_list = note_and_tag_list(request, tag)

  for note in notes_list:
    note.nt_tags = note.tags.all()
    note.summary = text_splitter(note.note_body, 15)

  note_number = pk
  note_presented = markdownify(notes_list.get(id=pk).note_body)
  note_tags = notes_list.get(id=pk).tags.names()
  template = loader.get_template('notes/user_notes.html')
  context = {
    'notes_list': notes_list,
    'tags_list': tags_list,
    'tag_name': tag,
    'note_number': note_number,
    'note_presented': note_presented,
    'note_tags': note_tags,
  }
  return HttpResponse(template.render(context, request))

@login_required
def get_search_results(request):
  if request.method == 'POST':
    tag = request.headers['Referer']
    tag = tag_extractor(tag)
    notes_list = []
    tags_list = []

    if tag != 'search_res':
      request.session['tag'] = tag
    else:
      tag = request.session['tag']
    notes_list, tags_list = note_and_tag_list(request, tag)
    
    

    print('=========')
    print('tag is:', tag)
    search_str = request.POST['search-bar']
    #notes_list = notes_list.filter(tags__name=tag)
    print('search string is: ', search_str)
    if len(notes_list) != 0:
      print('success')
    else:
      print('failure')

    notes_list = notes_list.filter(
      Q(note_title__contains=search_str) | Q(note_body__contains=search_str)
    )

    if len(notes_list) != 0:
      search_result_info = 'success'
    else:
      search_result_info = 'failure'
    print('info: ', search_result_info)
    for note in notes_list:
      note.nt_tags = note.tags.all()
      note.summary = text_splitter(note.note_body, 15)
    template = loader.get_template('notes/user_notes.html')
    context = {
      'notes_list': notes_list,
      'tags_list': tags_list,
      'tag_name': 'search_res',
      'search_str': search_str,
      'search_result_info': search_result_info
    }
    return HttpResponse(template.render(context, request))

@login_required
def get_search_results_with_note_detail(request, search_str, pk):
  notes_list = []
  tags_list = []
  #search_tag = 'search_res'
  tag = request.session['tag']
  notes_list, tags_list = note_and_tag_list(request, tag)

  
  notes_list = notes_list.filter(
      Q(note_title__contains=search_str) | Q(note_body__contains=search_str)
    )

  for note in notes_list:
    note.nt_tags = note.tags.all()
    note.summary = text_splitter(note.note_body, 15)

  note_number = pk
  note_presented = markdownify(notes_list.get(id=pk).note_body)
  note_tags = notes_list.get(id=pk).tags.names()
  template = loader.get_template('notes/user_notes.html')
  context = {
    'notes_list': notes_list,
    'tags_list': tags_list,
    'tag_name': 'search_res',
    'note_number': note_number,
    'note_presented': note_presented,
    'note_tags': note_tags,
    'search_str': search_str
  }
  return HttpResponse(template.render(context, request))


class AdminLogin(LoginView):
  template_name = 'notes/login_form.html'


class AdminLogout(LogoutView):
  pass


def signup(request):
  if request.method == 'POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      pw = form.cleaned_data.get('password1')
      user = authenticate(username=username, password=pw)
      login(request, user)
      return redirect('notes:home')
  else:
    form = SignUpForm()
  return render(request, 'notes/signup_form.html', {'form': form})


def home(request):
  user = request.user
  template = loader.get_template('notes/home.html')
  context = {
    'user': user,
  }
  return HttpResponse(template.render(context, request))

@login_required
def new_note(request):
  if request.method == 'POST':
    form = NoteForm(request.POST)
    if form.is_valid():
      newpost = form.save(commit=False)
      newpost.user = request.user
      messages.success(request, 'Note created successfully')
      #newpost.slug = slugify(newpost.title)
      newpost.save()
      # Without this next line the tags won't be saved.
      form.save_m2m()
      return redirect('notes:default_user_prof')
  else:
    form = NoteForm()

  context = {
    'form': form,
  }
  return render(request, 'notes/note_create_form.html', context)

@login_required
def update_note(request, pk):
  i_note_obj = Note.objects.get(pk=pk)
  i_note_title = i_note_obj.note_title
  i_note_body = i_note_obj.note_body
  i_note_tags = queryset_ext(i_note_obj.tags.names())
  i_data = {
    'note_title': i_note_title,
    'note_body': i_note_body,
    'tags': i_note_tags
  }
  if request.method == 'POST':
    form = NoteForm(request.POST, instance=i_note_obj)
    if form.is_valid():
      cd = form.cleaned_data
      obj = form.save(commit=False)
      if i_data['note_title'] != cd['note_title']:
        obj.note_title = cd['note_title']
      if i_data['note_body'] != cd['note_body']:
        obj.note_body = cd['note_body']
      obj.tags.set(''.join(cd['tags']))
      #newpost.slug = slugify(newpost.title)
      obj.save()
      # Without this next line the tags won't be saved.
      form.save_m2m()
      messages.success(request, 'Note updated successfully')
      return redirect('notes:default_user_prof')
    else:
      return HttpResponse(form.errors)
  else:
    form = NoteForm(i_data)

  context = {
    'form': form,
  }
  return render(request, 'notes/note_update_form.html', context)

@login_required
def trash_note(request, pk):
  note_obj = Note.objects.get(pk=pk)
  try:
    note_obj.trashed = True
    note_obj.save()
    messages.success(request, 'Note moved to bin successfully')
  except:
    messages.error(request, 'Note could not send to bin')
    
  return redirect('notes:default_user_prof')

@login_required
def untrash_note(request, pk):
  note_obj = Note.objects.get(pk=pk)
  try:
    note_obj.trashed = False
    note_obj.save()
    messages.success(request, 'Note retrieved from bin successfully')
  except:
    messages.error(request, 'Note could not retrieve from bin')
    
  return redirect('/profile/notes/trash/')

@login_required
def delete_note(request, pk):
  note_obj = Note.objects.get(pk=pk)
  try:
    note_obj.delete()
    messages.success(request, 'Note deleted successfully')
  except:
    messages.error(request, 'Note could not deleted')
    
  return redirect('/profile/notes/trash/')

notes/templates/notes/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="landing">
    <div class="container pt-3">
      <div class="row justify-content-md-center">
        <div class="lead col justify-content-center">
          <img class="rounded mx-auto d-block mb-3" src="{% static 'assets/journal-text.svg' %}" width="150" height="150" alt="">
          <h2 class="text-center">
            A Simple Note Taking Application
          </h2>
          {% if user.is_authenticated %}
            <a class="d-flex justify-content-center" href="/profile/notes/all">
              Go to Notes Page
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  <div>
{% endblock %}

notes/templates/notes/login_form.html
{% extends "base.html" %}
{% block content %}
  {% if form.errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Your username and password didn't match. Please try again.  
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        Your account doesn't have access to this page. To proceed,
        please login with an account that has access.   
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% else %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        Please login to see this page.   
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endif %}
  {% endif %}
  {% load static %}
  <div class="form-container container h-100 col-md-6 col-lg-4  m-auto container d-flex flex-column 
  justify-content-center">
    <div class="row mx-auto mb-4">
      <img src="{% static 'assets/journal-text.svg' %}" width="50" height="50" alt="">
    </div>
    <div class="row">
      <form class="form-login col" method="post" action="{% url 'notes:login' %}">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" class="form-control" id="username" placeholder="username" name="username">
        </div>
        <div class="form-group">
          <input type="password" class="form-control" id="password" placeholder="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary btn-block">Submit</button>
        <input type="hidden" name="next" value="{{ next }}">
      </form>
    </div>
  </div>
{% endblock %}

notes/templates/notes/note_create_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
{% load static %}
<script src="{% static 'notes/js/tagInput.min.js' %}"></script>
<a class="notes-link px-3 pb-2" href="/profile/notes/all/" role="button" aria-label="Notes-link">
  <img src="{% static 'assets/arrow-left.svg' %}" width="30" height="30" alt="">Back
</a>

<div class="bg-indigo h-md-100 note-container">
  <form method="post">
    {% csrf_token %}
    <div class="form-group col-md-6">
      {{ form.note_title|as_crispy_field }}
    </div>
    <div class="form-group col-md-6">
      <div id="div_id_note_tags" class="form-group">
        <label>
          Tags
        </label>
        </br>
        {{ form.tags }}
      </div>
    </div>
    <div class="form-group col">
      {{ form.note_body|as_crispy_field }}
    </div>
    <button type="submit" class="btn btn-primary mx-3">Create</button>
  </form>
  {{ form.media }}
</div>
{% endblock %}

notes/templates/notes/note_detail.html
{% load static %}
{% if note_presented %}
  <div class="border rounded bg-light col-md-6 col-lg-6 mx-auto col-lg-5 px-md-4 py-3">
    <a class="notes-link mb-3 mx-3" href="/profile/notes/{{ tag_name }}/" role="button" aria-label="Notes-link">
      <img src="{% static 'assets/arrow-left.svg' %}" width="25" height="25" alt="">Back
    </a>
    {% if tag_name != 'trash' %}
      {% if notes_list %}
        {% for note in notes_list %}
          {% if note_number == note.id %}
              <div class="note-content mt-3 mx-3">
                <div class="note-title">
                  <h3>{{ note.note_title }}</h3>
                </div>
                <div class="tags">
                  {% if note_tags %}
                    {% for tg in note_tags %}
                      <span class="badge badge-info p-1">{{ tg }}</span>
                    {% endfor %}
                  {% endif %}
                </div>
                <div class="note-body">
                  <p>
                    {% autoescape off %}
                      {{ note_presented }}
                    {% endautoescape %}
                  </p>
                </div>
              </div>
              <div class="note-edit-delete d-flex justify-content-center">
                <a class="btn btn-primary mr-3 edit-note position-relative" href="/update-note/{{ note.id }}" role="button">
                  Edit
                </a>
                <a class="btn btn-danger send-trash position-relative" href="/trash/{{ note.id }}" role="button">
                  Remove
                </a>
              </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% else %}
      {% if notes_list %}
        {% for note in notes_list %}
          {% if note_number == note.id %}
              <div class="note-content mt-3 mx-3">
                <div class="note-title">
                  <h3>{{ note.note_title }}</h3>
                </div>
                <div class="tags">
                  {% if note_tags %}
                    {% for tg in note_tags %}
                      <span class="badge badge-info p-1">{{ tg }}</span>
                    {% endfor %}
                  {% endif %}
                </div>
                <div class="note-body">
                  <p>
                    {% autoescape off %}
                      {{ note_presented }}
                    {% endautoescape %}
                  </p>
                </div>
              </div>
              <div class="note-edit-delete d-flex justify-content-center">
                <a class="btn btn-primary mr-3 edit-note position-relative" href="/untrash/{{ note.id }}" role="button">
                  Untrash
                </a>
                <a class="btn btn-danger send-trash position-relative" href="/delete/{{ note.id }}" role="button">
                  Delete
                </a>
              </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endif %}
  </div>
{% else %}
  <div class="border rounded bg-light d-none col-md-6 col-lg-6 mx-auto col-lg-5 px-md-4 py-3">
    
  </div>
{% endif %}

notes/templates/notes/note_update_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
{% load static %}
<script src="{% static 'notes/js/tagInput.min.js' %}"></script>
<a class="notes-link px-3 pb-2" href="/profile/notes/all/" role="button" aria-label="Notes-link">
  <img src="{% static 'assets/arrow-left.svg' %}" width="30" height="30" alt="">Back
</a>

<div class="bg-indigo h-md-100 note-container">
  <form method="post">
    {% csrf_token %}
    <div class="form-group col-md-6">
      {{ form.note_title|as_crispy_field }}
    </div>
    <div class="form-group col-md-6">
      <label>
        Tags
      </label>
      {{ form.tags }}
    </div>
    <div class="form-group col">
      {{ form.note_body|as_crispy_field }}
    </div>
    <button type="submit" class="btn btn-primary mx-3">Update</button>
  </form>
  {{ form.media }}
</div>
{% endblock %}

notes/templates/notes/signup_form.html
{% extends "base.html" %}
{% block content %}
  {% load static %}
  {% load crispy_forms_tags %}
  <div class="form-container container h-100 col-md-6 col-lg-4  m-auto container d-flex flex-column 
  justify-content-center">
    <div class="row">
      <form class="form-signup col" method="post" action="{% url 'notes:signup' %}">
        {% csrf_token %}
        {% for field in form %}
            {{ field|as_crispy_field }} </br>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        <input type="hidden" name="next" value="{{ next }}">
      </form>
    </div>
  </div>
{% endblock %}

notes/templates/notes/user_notes.html
{% extends "base.html" %}
{% block content %}
  {% load static %}
  {% load crispy_forms_tags %}
  <script src="{% static 'notes/js/scrollAdjuster.js' %}"></script>
  <div class="main-container row">
    <nav id="sidebarMenu" class="main-sidebar col-lg-2 d-lg-block bg-dark sidebar collapse">
      <div class="tags-sidebar sidebar-sticky overflow-auto">
        <ul class="nav flex-column tags-section">
          {% if tag_name == "all" %}
            <li class="nav-item">
              <a href="/profile/notes/all/" class="nav-link active">
                <img src="{% static 'assets/sticky-fill.svg' %}" width="20" height="20" alt="" style="margin-right: 0.5rem;">
                Notes
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="/profile/notes/all/" class="nav-link">
                <img src="{% static 'assets/sticky-fill.svg' %}" width="20" height="20" alt="" style="margin-right: 0.5rem;">
                Notes
              </a>
            </li>
          {% endif %}
          {% if tag_name == "trash" %}
            <li class="nav-item">
              <a href="/profile/notes/trash/" class="nav-link active">
                <img src="{% static 'assets/trash-fill.svg' %}" width="20" height="20" alt="" style="margin-right: 0.5rem;">
                Trash
                <span class="sr-only">(current)</span>
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="/profile/notes/trash/" class="nav-link">
                <img src="{% static 'assets/trash-fill.svg' %}" width="20" height="20" alt="" style="margin-right: 0.5rem;">
                Trash
              </a>
            </li>
          {% endif %}
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Tags</span>
          </h6>
          {% if tags_list %}
            {% for tag in tags_list %}
              {% if tag.name == tag_name %}
                <li class="nav-item">
                  <a href="/profile/notes/{{ tag_name }}/" class="nav-link d-flex justify-content-start active">
                    <img src="{% static 'assets/hash.svg' %}" width="20" height="20" alt="" style="margin-right: 0.5rem;">
                    <div class="tag-sidebar">{{ tag.name }}</div>
                    <span class="sr-only">(current)</span>
                  </a>  
                </li>
              {% else %}
                <li class="nav-item">
                  <a href="/profile/notes/{{ tag.name }}/" class="nav-link d-flex justify-content-start">
                    <img src="{% static 'assets/hash.svg' %}" width="20" height="20" alt="" style="margin-right: 0.5rem;">
                    <div class="tag-sidebar">{{ tag.name }}</div>
                  </a>  
                </li>
              {% endif %}
            {% endfor %}
          {% endif %}
        </ul>
      </div>
    </nav>
    {% include "notes/notes_list.html" %}
    {% if messages %}
      <div class="messages mx-auto">
        {% for message in messages %}
          {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% elif message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>  
          {% else %}
            <div class="alert alert-info alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div> 
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}   
    {% include "notes/note_detail.html" %}
  </div>
{% endblock %}